### ISSUE TITLE
Отсутствует обновление значения в мапе в классе Plaer

### ISSUE THREAD

**Issue by alfiya35** [alfiya35/GameStore#10]
# Описание
В методе возвращения суммарного количества времени, проигранного в игру не прописана логика, соответствующая условию, что нужно обновить значения в мапе игрока, добавив проигранное количество часов.

# Локация дефекта
  https://github.com/alfiya35/GameStore/blob/b5f38d427dca0ea409f0a6847b94e66839599375/src/main/java/ru/netology/Player.java#L33
Шаги воспроизведения
Открыть [код программы](https://github.com/alfiya35/GameStore/blob/main/src/main/java/ru/netology/Player.java#L28)
Найти метод возвращения суммарного количества часов, проигранное в одну игру
Ожидаемый результат: Логика прописана полностью и при тестировании метода, возвращает проигранное количество времени, переданное в параметры метода.
Фактический результат: При тестировании метода выдает ошибку(см скриншот)
 # Скриншот
![1](https://user-images.githubusercontent.com/101184598/171642096-8bbef10e-64fd-45d8-a446-be34ab110fd4.PNG)

# Окружение
Операционная система: Windows 7
IDE: IntelliJ IDEA
Java Open JDK 11.0.12

**Comment by bychkova** [comment]
Добавлена операция увеличения проигранного времени  в поле playedTime игрока
