### ISSUE TITLE
Метод addPlayTime не суммирует время, если игрок раньше играл в игру

### ISSUE THREAD

**Issue by bychkova** [alfiya35/GameStore#11]
# Описание
Если игрок уже играл в игру этого каталога, новое время не суммируется со старым.

# Шаги воспроизведения
1. Открыть [тестовый класс проекта](https://github.com/alfiya35/GameStore/blob/main/src/test/java/ru/netology/GameStoreTest.java).
2.  Создать новый каталог
3.  Создать нового игрока
4. Вызвать метод addPlayTime с параметром времени 3
5. Вызвать метод addPlayTime с параметром времени 4

*Ожидаемый результат:* 7
*Фактический результат:* 3
# Локализация
https://github.com/alfiya35/GameStore/blob/5e9d7e894608698f96cfa760dd33ea822107b3c2/src/main/java/ru/netology/GameStore.java#L48

Line 50 in [b5f38d4](https://github.com/alfiya35/GameStore/commit/b5f38d427dca0ea409f0a6847b94e66839599375)

 } else {

#Скриншот
![Снимок экрана 2022-06-10 в 16 41 14](https://user-images.githubusercontent.com/28761936/173079139-55e2fab3-154e-47f0-b9d5-785200478090.png)

# Окружение
* macOS High Siera 10.13.6 (17G14042)
* версия Java 11.0.12

**Comment by alfiya35** [comment]
Исправила
