### ISSUE TITLE
Метод getMostPlayer выводит null, если в каталоге только один игрок со временем 1

### ISSUE THREAD

**Issue by bychkova** [alfiya35/GameStore#12]
# Описание
Если в каталоге только один игрок и его время игры равно единице, метод не выводит этого игрока, выводит null.

# Шаги воспроизведения
1. Открыть [тестовый класс проекта](https://github.com/alfiya35/GameStore/blob/main/src/test/java/ru/netology/GameStoreTest.java).
2. В тесте создать новый каталог
3. В поле playedTime каталога добавить игрока с временем 1: ("Ваня", 1).
4. Вызвать метод getMostPlayer

*Ожидаемый результат:* Ваня
*Фактический результат:* null

#Скриншот
![Снимок экрана 2022-06-10 в 17 05 38](https://user-images.githubusercontent.com/28761936/173083362-547efbb8-faa2-404c-b226-1f7d85f199f8.png)

#Локализация
https://github.com/alfiya35/GameStore/blob/5e9d7e894608698f96cfa760dd33ea822107b3c2/src/main/java/ru/netology/GameStore.java#L59

# Окружение
* macOS High Siera 10.13.6 (17G14042)
* версия Java 11.0.12

**Comment by alfiya35** [comment]
исправила
