### ISSUE TITLE
Нет доступа к списку игр каталога List<Game> games в классе Game store

### ISSUE THREAD

**Issue by bychkova** [alfiya35/GameStore#2]
# Описание
Невозможно протестировать методы publishGame и containsGame, так нет доступа к полю List<Game> games

# Шаги воспроизведения
1. Открыть [тестовый класс проекта](https://github.com/alfiya35/GameStore/blob/main/src/test/java/ru/netology/GameStoreTest.java) в IDE.
2.  В тесте shouldAddGame создать новый объект store типа Game store.
3. Создать новый объект game типа Game.
4. Переменной game присвоить результат вызова метода store.publishGame с параметрами ("Нетология Баттл Онлайн", "Аркады")
5. Проверить, содержит ли поле games объекта store добавленную игру, вызвав встроенный метод contains для списков `store.games.contains(game)`

*Ожидаемый результат:*  метод contains работает, нет предупреждений
*Фактический результат:* ошибка доступа к полю games

# Скриншот
![Снимок экрана 2022-05-28 в 17 33 59](https://user-images.githubusercontent.com/28761936/170830494-9812e3c8-dc04-4f6a-898e-a714139b746d.png)

# Окружение
* macOS High Siera 10.13.6 (17G14042)
* версия Java 11.0.12

**Comment by alfiya35** [comment]
Открыла доступ к полям, сделав модификатор доступа к ним protected
