### ISSUE TITLE
Нет доступа к к информации о сыграном времени в классе Game store

### ISSUE THREAD

**Issue by bychkova** [alfiya35/GameStore#3]
# Описание
Невозможно протестировать методы addPlayTime и getMostPlayer, так нет доступа к полю Map playedTime

# Шаги воспроизведения
1. Открыть [тестовый класс проекта](https://github.com/alfiya35/GameStore/blob/main/src/test/java/ru/netology/GameStoreTest.java) в IDE.
2. В тесте shouldAddPlayTimeFirstPlay создать новый объект store типа Game store.
3. Создать новый объект firstPlayer типа Player с именем ("First").
4. Вызвать метод `store.addPlayTime(firstPlayer.getName(), 3)`
5. Проверить, содержит ли поле playedTime время, сыграное игроком firstPlayer.

*Ожидаемый результат:* метод get работает, нет предупреждений
*Фактический результат:* ошибка доступа к полю playedTime

# Скриншот
![Снимок экрана 2022-05-28 в 18 16 56](https://user-images.githubusercontent.com/28761936/170831915-fa477259-dd24-4e18-aa65-eedf98b4a9f2.png)

# Окружение
* macOS High Siera 10.13.6 (17G14042)
* версия Java 11.0.12

**Comment by alfiya35** [comment]
Открыла доступ к полям, сделав модификатор доступа к ним protected
