### ISSUE TITLE
Не реализован метод getSumPlayedTime в классе Game Store

### ISSUE THREAD

**Issue by bychkova** [alfiya35/GameStore#4]
# Описание
Не реализован метод получения общего времени, проведенного за играми этого каталога

# Шаги воспроизведения
1. Открыть [класс Game Store](https://github.com/alfiya35/GameStore/blob/main/src/main/java/ru/netology/GameStore.java) в IDE.
2. Найти метод getSumPlayedTime

*Ожидаемый результат:* написана логика кода
*Фактический результат:* код всегда возвращает null

#Скриншот
![Снимок экрана 2022-05-28 в 18 34 56](https://user-images.githubusercontent.com/28761936/170832221-e5ca2a24-0b8b-424e-b748-820c975c9310.png)

# Окружение
* macOS High Siera 10.13.6 (17G14042)
* версия Java 11.0.12

**Comment by alfiya35** [comment]
Прописана логика метода
