### ISSUE TITLE
Неполный метод добавления элемента в классе Player

### ISSUE THREAD

**Issue by alfiya35** [alfiya35/GameStore#5]
# Описание
Логика метода добавления игры игроку прописана не полностью

# Локация дефекта
https://github.com/alfiya35/GameStore/blob/b5f38d427dca0ea409f0a6847b94e66839599375/src/main/java/ru/netology/Player.java#L24

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/alfiya35/GameStore/blob/main/src/main/java/ru/netology/Player.java)
2. Найти метод добавления игры игроку

* Ожидаемый результат: Логика метода прописана полностью и тесты проходят.
* Фактический результат: Честь логики отсутствует:  если игра уже была, никаких изменений происходить не должно

# Локализация дефекта
![1](https://user-images.githubusercontent.com/101184598/171637208-d46a8c71-a20a-4a5b-b47e-b438c6228cff.PNG)

# Окружение 
* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA
* **Java** Open JDK 11.0.12

**Comment by bychkova** [comment]
Добавлено условие добавления игры
