### ISSUE TITLE
Отсутствие логики об ошибке в классе Player

### ISSUE THREAD

**Issue by alfiya35** [alfiya35/GameStore#6]
# Описание
В методе возвращения суммарного количества часов, проигранное в одну  игру, не прописана логика выдачи ошибки(RuntimeException), в случае если такой игры нет, если она не была установлена. 

# Локация дефекта
https://github.com/alfiya35/GameStore/blob/b5f38d427dca0ea409f0a6847b94e66839599375/src/main/java/ru/netology/Player.java#L33
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/alfiya35/GameStore/blob/main/src/main/java/ru/netology/Player.java#L28)
2. Найти метод возвращения суммарного количества часов, проигранное в одну игру

*Ожидаемый результат:* Логика прописана полностью и при тестировании метода, указав несуществующую игру, программа выдает ошибку, что указанной игры нет.
*Фактический результат:* Логика прописана не полностью и часть метода, где должна быть логика, которая выдает ошибку RuntimeException  отсутствует.

# Окружение
* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA
* **Java** Open JDK 11.0.12

**Comment by bychkova** [comment]
Добавлен RuntimeException
