### ISSUE TITLE
Отсутствие части логики в методе в классе Player

### ISSUE THREAD

**Issue by alfiya35** [alfiya35/GameStore#7]
# Описание
В методе суммирования времени проигранного игроком в игры одного жанра прописана лишняя  логика. Так как условия else  не будет выполнено при тестировании этого метода. 
# Локация дефекта
https://github.com/alfiya35/GameStore/blob/b5f38d427dca0ea409f0a6847b94e66839599375/src/main/java/ru/netology/Player.java#L50
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/alfiya35/GameStore/blob/main/src/main/java/ru/netology/Player.java)
2. Найти метод суммирования времени проигранного игроком в игры одного жанра

* Ожидаемый результат: При тестировании метода, при передаче в параметры данные жанра игры, метод отдает время проигранное этим игроком.
* Фактический результат: Тесты проходят и метода работает, Но честь логики в методе не используется.

# Окружение 
* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA
* **Java** Open JDK 11.0.12

**Comment by bychkova** [comment]
Добавлена логика обработки ситуации, когда игрок не играл в игры данного жанра
