### ISSUE TITLE
Отсутствие основной части метода в классе Player

### ISSUE THREAD

**Issue by alfiya35** [alfiya35/GameStore#8]
# Описание
В методе, который  принимает жанр и возвращает игру этого жанра, в которую играли больше всего, отсутствует основная часть логики метода.

# Локация дефекта
https://github.com/alfiya35/GameStore/blob/b5f38d427dca0ea409f0a6847b94e66839599375/src/main/java/ru/netology/Player.java#L59

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/alfiya35/GameStore/blob/main/src/main/java/ru/netology/Player.java)
2. Найти метод, который возвращает игру одного жанра, в которую играли больше всего.

* Ожидаемый результат: Логика метода прописана полностью и тесты проходят.
* Фактический результат: Честь логики отсутствует. Есть только название метода, параметры которые он принимает и есть логика выполнения условия когда в игры этого жанра не играли,  то возвращается null 

# Окружение 
* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA
* **Java** Open JDK 11.0.12

**Comment by bychkova** [comment]
Реализована логика метода mostPlayerByGenre
